name: Docker CI for Flask App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Tambahkan batas waktu agar tidak infinite

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Run with docker-compose
      run: |
        docker compose up -d --build
        echo "Waiting for Flask app to be ready..."
        for i in {1..10}; do
          if curl --fail http://localhost:5000; then
            echo "Flask is up!"
            break
          else
            echo "Flask not ready, retrying in 5s..."
            sleep 5
          fi
        done

    - name: Stop containers
      run: docker compose down
